### ISSUE TITLE
Information on addition of new facts.

### ISSUE THREAD

**Issue by laxuscullen** [AnimuAPI/Docs#1]
Just found out about this API and I am absolutely loving the /fact endpoint. The waifu one is amazing as well. My question is, do you plan to update the facts often? Right now it is only 121 and soon enough one would have seen all of them.

Thank you for your hard work and time. Looking forward to your reply.

**Comment by notkyoyo** [comment]
Currently, I'm working on the API to make it **OPEN SOURCE**. But yeah I really do plan to update it more frequently.
